interface DeployStepProps {
  modelId: string;
  name: string;
  isEdit: boolean;
  onSave: () => void;
  saving: boolean;
  error: string | null;
}

export default function DeployStep({
  modelId,
  name,
  isEdit,
  onSave,
  saving,
  error,
}: DeployStepProps) {
  return (
    <div className="flex flex-col gap-4">
      <h3 className="text-sm font-semibold text-foreground">Step 7: Deploy</h3>

      {/* Confirmation card */}
      <div className="border border-border rounded bg-surface p-4">
        <div className="flex items-start gap-3">
          <div className="w-8 h-8 rounded-full bg-accent/20 flex items-center justify-center shrink-0 mt-0.5">
            <svg className="w-4 h-4 text-accent" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
            </svg>
          </div>
          <div className="flex flex-col gap-1">
            <span className="text-sm font-semibold text-foreground">
              {isEdit ? "Update Existing Model" : "Create New Model"}
            </span>
            <span className="text-xs text-muted">
              {isEdit
                ? `The model "${name}" (${modelId}) will be updated with your changes.`
                : `A new detection model "${name}" (${modelId}) will be created.`}
            </span>
          </div>
        </div>
      </div>

      {/* Impact note */}
      <div className="border border-border rounded bg-surface-elevated p-3">
        <div className="text-[11px] font-medium text-muted uppercase tracking-wider mb-1.5">
          Impact
        </div>
        <ul className="flex flex-col gap-1 text-xs text-muted list-disc list-inside">
          <li>This model will be available in the pipeline after saving</li>
          <li>The detection engine will include this model in future evaluation runs</li>
          <li>Alerts generated by this model will appear in the Risk Case Manager</li>
        </ul>
      </div>

      {/* Save button */}
      <div className="flex items-center gap-3">
        <button
          onClick={onSave}
          disabled={saving}
          className="px-4 py-2 bg-accent text-white rounded text-xs font-medium hover:bg-accent/80 disabled:opacity-50 transition-colors"
        >
          {saving ? "Saving..." : isEdit ? "Save Changes" : "Deploy Model"}
        </button>
        {saving && (
          <div className="w-3 h-3 border-2 border-accent border-t-transparent rounded-full animate-spin" />
        )}
      </div>

      {/* Error display */}
      {error && (
        <div className="p-3 rounded border border-destructive/30 bg-destructive/10 text-xs text-destructive">
          {error}
        </div>
      )}
    </div>
  );
}
