import type { ViewTrace } from "../architectureRegistryTypes";

export const aiAssistantSections: ViewTrace = {
  viewId: "assistant",
  viewName: "AI Assistant",
  route: "/assistant",
  sections: [
    {
      id: "assistant.chat-panel",
      displayName: "Chat Panel",
      viewId: "assistant",
      description:
        "Full-page chat UI with message bubbles, code blocks, and SQL execution. Supports both live Claude API and mock demo mode with pre-scripted sequences.",
      files: [
        { path: "frontend/src/views/AIAssistant/index.tsx", role: "Main AI assistant view" },
        { path: "frontend/src/views/AIAssistant/ChatPanel.tsx", role: "Chat UI with message rendering" },
        { path: "backend/api/ai.py", role: "AI chat endpoint (mock or live)" },
      ],
      stores: [],
      apis: [
        {
          method: "POST",
          path: "/api/ai/chat",
          role: "Processes chat messages via mock or live AI",
          routerFile: "backend/api/ai.py",
        },
      ],
      dataSources: [
        {
          path: "workspace/metadata/ai_mock_sequences.json",
          category: "config",
          role: "Pre-scripted mock AI conversation sequences for demo mode",
        },
      ],
      technologies: [],
      metadataMaturity: "mostly-metadata-driven",
      maturityExplanation:
        "Mock sequences are metadata-driven configuration. AI context auto-generates from live metadata state via /api/ai/context-summary (entities, models, calcs, settings, format rules, navigation). Chat UI and message parsing are code-driven.",
      metadataOpportunities: [
        "Define chat capabilities as metadata (available tools, SQL access scope)",
      ],
    },
    {
      id: "assistant.mock-player",
      displayName: "Mock Player",
      viewId: "assistant",
      description:
        "Scenario selector for mock demo mode. Allows choosing from pre-scripted conversation sequences to demonstrate AI capabilities without live API access.",
      files: [
        { path: "frontend/src/views/AIAssistant/MockPlayer.tsx", role: "Mock scenario selector and player" },
        { path: "backend/api/ai.py", role: "Returns available mock sequences" },
      ],
      stores: [],
      apis: [
        {
          method: "GET",
          path: "/api/ai/mock-sequences",
          role: "Returns available mock conversation sequences",
          routerFile: "backend/api/ai.py",
        },
      ],
      dataSources: [
        {
          path: "workspace/metadata/ai_mock_sequences.json",
          category: "config",
          role: "Mock sequence definitions with messages and SQL",
        },
      ],
      technologies: [],
      metadataMaturity: "mostly-metadata-driven",
      maturityExplanation:
        "Mock sequences are defined in a JSON config file. Adding new sequences does not require code changes.",
    },
    {
      id: "assistant.query-preview",
      displayName: "Query Preview",
      viewId: "assistant",
      description:
        "SQL execution results panel within AI assistant. Displays results when the AI generates and executes SQL queries as part of the conversation.",
      files: [
        { path: "frontend/src/views/AIAssistant/QueryPreview.tsx", role: "SQL query results display" },
        { path: "backend/api/query.py", role: "Executes SQL queries from AI" },
      ],
      stores: [],
      apis: [
        {
          method: "POST",
          path: "/api/query/execute",
          role: "Executes SQL queries generated by AI",
          routerFile: "backend/api/query.py",
        },
      ],
      dataSources: [],
      technologies: [{ name: "AG Grid", role: "Dynamic result grid for AI query output" }],
      metadataMaturity: "infrastructure",
      maturityExplanation:
        "Infrastructure component for displaying SQL results. Query execution is a runtime operation.",
    },
  ],
};
